-- CURSO_FK
ALTER TABLE CURSO ADD CONSTRAINT FK1_CURSO FOREIGN KEY (ID_PROFESSOR) REFERENCES  USUARIO(ID);

-- AULA_FK
ALTER TABLE AULA ADD CONSTRAINT FK1_AULA FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID);
