-- CURSO_FK
ALTER TABLE CURSO ADD CONSTRAINT FK1_CURSO FOREIGN KEY (ID_PROFESSOR) REFERENCES  USUARIO(ID);

-- AULA_FK
ALTER TABLE AULA ADD CONSTRAINT FK1_AULA FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID);

-- MATRICULA_FK
ALTER TABLE MATRICULA ADD CONSTRAINT FK1_MATRICULA FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID);
ALTER TABLE MATRICULA ADD CONSTRAINT FK2_MATRICULA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);

-- ARQUIVO_FK
ALTER TABLE AULA_ARQUIVO ADD CONSTRAINT FK1_AULA_ARQUIVO FOREIGN KEY (ID_AULA) REFERENCES AULA(ID);
ALTER TABLE AULA_ARQUIVO ADD CONSTRAINT FK2_AULA_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES ARQUIVO(ID);
