--elimina caso exista o banco de dados chamado tcc (Rodar com usuário com privilégios de DBA)
drop user tcc cascade
/
-- Cria o usuário tcc com a senha teste e concede privilégios de DBA (Rodar com usuário com privilégios de DBA)
CREATE USER tcc IDENTIFIED BY teste
/
grant dba to tcc
/

-- Cria as tables e os relacioanamentos
CREATE sequence hibernate_sequence START WITH 1 ORDER CACHE 1000 INCREMENT BY 1;
CREATE TABLE USUARIO (
    ID NUMBER NOT NULL,
    NOME_COMPLETO VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    LOGIN VARCHAR2(200) NOT NULL,
    SENHA VARCHAR2(150) NOT NULL,
    DATA_INCLUSAO DATE NOT NULL,
    PERFIL NUMBER NOT NULL
);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID);
CREATE TABLE CURSO (
    ID NUMBER NOT NULL,
    TITULO VARCHAR2(200),
    DATA DATE NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL,
    ID_PROFESSOR NUMBER NOT NULL
);
ALTER TABLE CURSO ADD CONSTRAINT CURSO_PK PRIMARY KEY (ID);
ALTER TABLE CURSO ADD CONSTRAINT FK1_CURSO FOREIGN KEY (ID_PROFESSOR) REFERENCES  USUARIO(ID);

CREATE TABLE MATRICULA (
    ID NUMBER NOT NULL,
    ID_CURSO NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    DATA_MATRICULA DATE NOT NULL
);
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_PK PRIMARY KEY (ID);
ALTER TABLE MATRICULA ADD CONSTRAINT FK1_MATRICULA FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID);
ALTER TABLE MATRICULA ADD CONSTRAINT FK2_MATRICULA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
/
CREATE TABLE AULA (
    ID NUMBER NOT NULL,
    NUMERO NUMBER,
    TITULO VARCHAR2(200),
    DESCRICAO VARCHAR2(1000) NOT NULL,
    ID_CURSO NUMBER NOT NULL
);
ALTER TABLE AULA ADD CONSTRAINT AULA_PK PRIMARY KEY (ID);
ALTER TABLE AULA ADD CONSTRAINT FK1_AULA FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID);

CREATE TABLE ARQUIVO (
    ID NUMBER NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    CAMINHO VARCHAR2(200) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    TAMANHO NUMBER NOT NULL,
    DATA_UPLOAD DATE NOT NULL
);
ALTER TABLE ARQUIVO ADD CONSTRAINT ARQUIVO_PK PRIMARY KEY (ID);

CREATE TABLE AULA_ARQUIVO (
    ID NUMBER NOT NULL,
    ID_AULA NUMBER NOT NULL,
    ID_ARQUIVO NUMBER NOT NULL
);
ALTER TABLE AULA_ARQUIVO ADD CONSTRAINT AULA_ARQUIVO_PK PRIMARY KEY (ID);
ALTER TABLE AULA_ARQUIVO ADD CONSTRAINT FK1_AULA_ARQUIVO FOREIGN KEY (ID_AULA) REFERENCES AULA(ID);
ALTER TABLE AULA_ARQUIVO ADD CONSTRAINT FK2_AULA_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES ARQUIVO(ID)
/
COMMIT
/

