CREATE TABLE USUARIO (
    ID NUMBER NOT NULL,
    NOME_COMPLETO VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    LOGIN VARCHAR2(200) NOT NULL,
    SENHA VARCHAR2(150) NOT NULL,
    DATA_INCLUSAO DATE NOT NULL,
    PERFIL NUMBER NOT NULL
);

CREATE TABLE CURSO (
    ID NUMBER NOT NULL,
    TITULO VARCHAR2(200),
    DATA DATE NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL,
    ID_PROFESSOR NUMBER NOT NULL
);

CREATE TABLE AULA (
    ID NUMBER NOT NULL,
    DESCRICAO  VARCHAR2(500) NOT NULL,
    ID_CURSO NUMBER NOT NULL
);



