CREATE TABLE USUARIO (
    ID NUMBER NOT NULL,
    NOME_COMPLETO VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    LOGIN VARCHAR2(200) NOT NULL,
    SENHA VARCHAR2(150) NOT NULL,
    DATA_INCLUSAO DATE NOT NULL,
    PERFIL NUMBER NOT NULL
);

CREATE TABLE CURSO (
    ID NUMBER NOT NULL,
    TITULO VARCHAR2(200),
    DATA DATE NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL,
    ID_PROFESSOR NUMBER NOT NULL
);

CREATE TABLE AULA (
    ID NUMBER NOT NULL,
    NUMERO NUMBER,
    TITULO VARCHAR2(200),
    DESCRICAO VARCHAR2(1000) NOT NULL,
    ID_CURSO NUMBER NOT NULL
);

CREATE TABLE MATRICULA (
    ID NUMBER NOT NULL,
    ID_CURSO NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    DATA_MATRICULA DATE NOT NULL
);

CREATE TABLE ARQUIVO (
    ID NUMBER NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    CAMINHO VARCHAR2(200) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    TAMANHO NUMBER NOT NULL,
    DATA_UPLOAD DATE NOT NULL
);

CREATE TABLE AULA_ARQUIVO (
    ID NUMBER NOT NULL,
    ID_AULA NUMBER NOT NULL,
    ID_ARQUIVO NUMBER NOT NULL
);




