-- Criação da tabela USUARIO
CREATE TABLE USUARIO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_COMPLETO VARCHAR2(100),
    EMAIL VARCHAR2(100),
    LOGIN VARCHAR2(50),
    SENHA VARCHAR2(50),
    DATA_INCLUSAO DATE,
    PERFIL VARCHAR2(20),
    TIPO_USUARIO VARCHAR2(20) NOT NULL
);

-- Criação da tabela CURSO
CREATE TABLE CURSO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(200),
    DESCRICAO CLOB,
    PROFESSOR_ID NUMBER
);

-- Criação da tabela MATRICULA
CREATE TABLE MATRICULA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    ID_CURSO NUMBER NOT NULL,
    DATA_MATRICULA DATE
);


-- Constraints de chave estrangeira
ALTER TABLE CURSO
ADD CONSTRAINT FK_CURSO_PROFESSOR
FOREIGN KEY (PROFESSOR_ID)
REFERENCES USUARIO(ID);

CREATE TABLE AULA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(255) NOT NULL,
    DESCRICAO CLOB NOT NULL,
    URL_CONTEUDO VARCHAR2(500) NOT NULL,
    CURSO_ID NUMBER NOT NULL,
    PROFESSOR_ID NUMBER NOT NULL
);

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID);

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_CURSO
FOREIGN KEY (ID_CURSO)
REFERENCES CURSO(ID);

-- Relacionamento com a tabela CURSO
ALTER TABLE AULA
ADD CONSTRAINT FK_AULA_CURSO
FOREIGN KEY (CURSO_ID)
REFERENCES CURSO(ID);

-- Relacionamento com a tabela USUARIO (professor)
ALTER TABLE AULA
ADD CONSTRAINT FK_AULA_PROFESSOR
FOREIGN KEY (PROFESSOR_ID)
REFERENCES USUARIO(ID);

ALTER TABLE AULA ADD URL_VIDEO VARCHAR2(500);

ALTER TABLE AULA ADD URL_VIDEO VARCHAR2(500);

ALTER TABLE CURSO ADD URL_PDF VARCHAR2(255);

ALTER TABLE curso ADD url_video VARCHAR2(255);

